// <auto-generated />
using System;
using FoodSafety.MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodSafety.MVC.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323135355_1.4")]
    partial class _14
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("FoodSafety.Library.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("FollowUps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateOnly(2026, 2, 1),
                            InspectionId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DueDate = new DateOnly(2026, 1, 15),
                            InspectionId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            DueDate = new DateOnly(2026, 1, 20),
                            InspectionId = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            DueDate = new DateOnly(2026, 2, 10),
                            InspectionId = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            DueDate = new DateOnly(2026, 2, 28),
                            InspectionId = 14,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DueDate = new DateOnly(2025, 12, 20),
                            InspectionId = 17,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            DueDate = new DateOnly(2025, 12, 1),
                            InspectionId = 19,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            ClosedDate = new DateOnly(2026, 3, 15),
                            DueDate = new DateOnly(2026, 3, 10),
                            InspectionId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            ClosedDate = new DateOnly(2025, 11, 20),
                            DueDate = new DateOnly(2025, 11, 1),
                            InspectionId = 22,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            ClosedDate = new DateOnly(2025, 12, 1),
                            DueDate = new DateOnly(2025, 11, 15),
                            InspectionId = 24,
                            Status = 1
                        });
                });

            modelBuilder.Entity("FoodSafety.Library.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutCome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PremisesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PremisesId");

                    b.ToTable("Inspections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InspectionDate = new DateOnly(2026, 3, 1),
                            Notes = "Hygiene issues found",
                            OutCome = 1,
                            PremisesId = 1,
                            Score = 45
                        },
                        new
                        {
                            Id = 2,
                            InspectionDate = new DateOnly(2026, 3, 3),
                            Notes = "Minor issues noted",
                            OutCome = 0,
                            PremisesId = 2,
                            Score = 82
                        },
                        new
                        {
                            Id = 3,
                            InspectionDate = new DateOnly(2026, 3, 5),
                            Notes = "All clear",
                            OutCome = 0,
                            PremisesId = 3,
                            Score = 91
                        },
                        new
                        {
                            Id = 4,
                            InspectionDate = new DateOnly(2026, 3, 7),
                            Notes = "Multiple violations",
                            OutCome = 1,
                            PremisesId = 4,
                            Score = 38
                        },
                        new
                        {
                            Id = 5,
                            InspectionDate = new DateOnly(2026, 3, 10),
                            Notes = "Adequate standards",
                            OutCome = 0,
                            PremisesId = 5,
                            Score = 74
                        },
                        new
                        {
                            Id = 6,
                            InspectionDate = new DateOnly(2026, 3, 12),
                            Notes = "Storage problems",
                            OutCome = 1,
                            PremisesId = 6,
                            Score = 55
                        },
                        new
                        {
                            Id = 7,
                            InspectionDate = new DateOnly(2026, 3, 15),
                            Notes = "Good overall",
                            OutCome = 0,
                            PremisesId = 7,
                            Score = 88
                        },
                        new
                        {
                            Id = 8,
                            InspectionDate = new DateOnly(2026, 3, 18),
                            Notes = "Minor temperature issues",
                            OutCome = 0,
                            PremisesId = 8,
                            Score = 62
                        },
                        new
                        {
                            Id = 9,
                            InspectionDate = new DateOnly(2026, 2, 5),
                            Notes = "Pest control needed",
                            OutCome = 1,
                            PremisesId = 9,
                            Score = 41
                        },
                        new
                        {
                            Id = 10,
                            InspectionDate = new DateOnly(2026, 2, 10),
                            Notes = "Satisfactory",
                            OutCome = 0,
                            PremisesId = 10,
                            Score = 78
                        },
                        new
                        {
                            Id = 11,
                            InspectionDate = new DateOnly(2026, 2, 14),
                            Notes = "Serious violations",
                            OutCome = 1,
                            PremisesId = 11,
                            Score = 33
                        },
                        new
                        {
                            Id = 12,
                            InspectionDate = new DateOnly(2026, 2, 20),
                            Notes = "Excellent",
                            OutCome = 0,
                            PremisesId = 12,
                            Score = 95
                        },
                        new
                        {
                            Id = 13,
                            InspectionDate = new DateOnly(2026, 1, 8),
                            Notes = "Improved since last visit",
                            OutCome = 0,
                            PremisesId = 1,
                            Score = 60
                        },
                        new
                        {
                            Id = 14,
                            InspectionDate = new DateOnly(2026, 1, 15),
                            Notes = "Cross contamination risk",
                            OutCome = 1,
                            PremisesId = 2,
                            Score = 49
                        },
                        new
                        {
                            Id = 15,
                            InspectionDate = new DateOnly(2026, 1, 22),
                            Notes = "Good hygiene",
                            OutCome = 0,
                            PremisesId = 3,
                            Score = 85
                        },
                        new
                        {
                            Id = 16,
                            InspectionDate = new DateOnly(2025, 12, 3),
                            Notes = "Acceptable",
                            OutCome = 0,
                            PremisesId = 4,
                            Score = 72
                        },
                        new
                        {
                            Id = 17,
                            InspectionDate = new DateOnly(2025, 12, 10),
                            Notes = "Temperature violations",
                            OutCome = 1,
                            PremisesId = 5,
                            Score = 44
                        },
                        new
                        {
                            Id = 18,
                            InspectionDate = new DateOnly(2025, 12, 18),
                            Notes = "Very good",
                            OutCome = 0,
                            PremisesId = 6,
                            Score = 90
                        },
                        new
                        {
                            Id = 19,
                            InspectionDate = new DateOnly(2025, 11, 5),
                            Notes = "Deep clean required",
                            OutCome = 1,
                            PremisesId = 7,
                            Score = 37
                        },
                        new
                        {
                            Id = 20,
                            InspectionDate = new DateOnly(2025, 11, 12),
                            Notes = "Well maintained",
                            OutCome = 0,
                            PremisesId = 8,
                            Score = 81
                        },
                        new
                        {
                            Id = 21,
                            InspectionDate = new DateOnly(2025, 11, 20),
                            Notes = "Minor issues",
                            OutCome = 0,
                            PremisesId = 9,
                            Score = 66
                        },
                        new
                        {
                            Id = 22,
                            InspectionDate = new DateOnly(2025, 10, 8),
                            Notes = "Drainage problems",
                            OutCome = 1,
                            PremisesId = 10,
                            Score = 53
                        },
                        new
                        {
                            Id = 23,
                            InspectionDate = new DateOnly(2025, 10, 15),
                            Notes = "Satisfactory",
                            OutCome = 0,
                            PremisesId = 11,
                            Score = 77
                        },
                        new
                        {
                            Id = 24,
                            InspectionDate = new DateOnly(2025, 10, 22),
                            Notes = "Critical violations",
                            OutCome = 1,
                            PremisesId = 12,
                            Score = 29
                        },
                        new
                        {
                            Id = 25,
                            InspectionDate = new DateOnly(2025, 9, 10),
                            Notes = "All standards met",
                            OutCome = 0,
                            PremisesId = 1,
                            Score = 88
                        });
                });

            modelBuilder.Entity("FoodSafety.Library.Premises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Premises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Main St",
                            Name = "The Golden Spoon",
                            RiskRating = 2,
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Oak Ave",
                            Name = "Burger Barn",
                            RiskRating = 1,
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 3,
                            Address = "78 River Rd",
                            Name = "Pizza Palace",
                            RiskRating = 0,
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 4,
                            Address = "23 Elm St",
                            Name = "Sushi Stop",
                            RiskRating = 2,
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 5,
                            Address = "9 Hill Rd",
                            Name = "The Breakfast Club",
                            RiskRating = 1,
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 6,
                            Address = "34 Lake Dr",
                            Name = "Noodle House",
                            RiskRating = 0,
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 7,
                            Address = "56 Park Ln",
                            Name = "Taco Town",
                            RiskRating = 2,
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 8,
                            Address = "11 Beach Rd",
                            Name = "The Green Leaf",
                            RiskRating = 1,
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 9,
                            Address = "67 North St",
                            Name = "Curry Corner",
                            RiskRating = 0,
                            Town = "Galway"
                        },
                        new
                        {
                            Id = 10,
                            Address = "89 West Ave",
                            Name = "Fish & Chips Co",
                            RiskRating = 2,
                            Town = "Galway"
                        },
                        new
                        {
                            Id = 11,
                            Address = "14 East Rd",
                            Name = "The Sandwich Bar",
                            RiskRating = 1,
                            Town = "Galway"
                        },
                        new
                        {
                            Id = 12,
                            Address = "30 South St",
                            Name = "Sweet Treats",
                            RiskRating = 0,
                            Town = "Galway"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoodSafety.Library.FollowUp", b =>
                {
                    b.HasOne("FoodSafety.Library.Inspection", "Inspection")
                        .WithMany("FollowUps")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("FoodSafety.Library.Inspection", b =>
                {
                    b.HasOne("FoodSafety.Library.Premises", "Premises")
                        .WithMany("Inspections")
                        .HasForeignKey("PremisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premises");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodSafety.Library.Inspection", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("FoodSafety.Library.Premises", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
